### ISSUE TITLE
Core dump on ARMv7 when run by mdbook

### ISSUE THREAD

**Issue by whooie** [lzanini/mdbook-katex#16]
I'm trying to serve an mdbook from a Raspberry Pi 4 (B) with Arch Linux ARM installed and the process exits because it can't run mdbook-katex:

```
$ mdbook serve [...]
2021-07-13 10:24:45 [INFO] (mdbook::book): Book building has started
2021-07-13 10:24:45 [ERROR] (mdbook::utils): Error: The "katex" preprocessor exited unsuccessfully with signal: 11 (core dumped) status
```

Running `mdbook-katex --version` is fine, however. I don't have any other information about what could be going on. It's worth noting that this doesn't happen with other preprocessors I'm using, e.g. mdbook-toc.

Steps to reproduce:
- Install mdbook
- Install mdbook-katex either using cargo or cross-compiling for target armv7-unknown-linux-gnueabihf
- Run mdbook

**Comment by kevaundray** [comment]
The problem seems to be in quickjs. mdbook-katex uses the `katex` dependency which in turn uses `quickjs` as a backend.

This problem only seems to be reproducible on MacBooks, I did not look into the reason as to why, however the debugger points to  an empty stack frame in C code when the program tries to initialise the `KATEX` global variable in katex-rs.

### Reproducing

If on a MacBook, you can reproduce this issue by cloning mdbook-katex and running `cargo test`.  The following tests will fail with a SIGSEGV invalid memory reference.

- test_macros_without_argument
- test_macros_with_argument
- test_display_rendering

### Quick Fix (locally)

The quick fix will involve using a different backend to the default `quickjs` one in katex-rs.

1. Clone mdbook-katex
2. The Cargo.toml file will have a katex dependency. Replace it with: `katex = { version = "0.4.1", default-features = false, features = ["duktape"] }`
3. run `cargo install --path .`

The second step turns off the default features which is quickjs and in turn compiles with duktape. The third line will overwrite the mdboook-katex binary with the modified version.

**Note**

The output from quickjs and duktape differ slightly and so you will still have a failing test `test_display_rendering`. It is okay to ignore this, semantically the output is the same.

### Possible Solution

This seems to be a problem with katex-rs and not mdbook-katex.  A solution for this crate would be to use the `duktape` backend by default since it works on MacOS and I am assuming on Linux and Window.

Alternatively, you could enable `quickjs` by default and feature gate `duktape` for MacOS

**Comment by SichangHe** [comment]
Is this problem still there? I don't have a Raspberry Pi to test it.

**Comment by hwf1324** [comment]
这也可以用于修复 Android 上的 Termux 无法 `cargo install mdbook-katex` 的错误。

**Comment by SichangHe** [comment]
Does this problem still exist? Where? Is it on all ARM platforms?
I think we just need to specify the features for the `katex` crate correctly.

**Comment by SichangHe** [comment]
Using `duktape` is not a good solution because [it cannot render some expressions](https://github.com/xu-cheng/katex-rs/issues/12).

It should only be used to mitigate the build failures on specific platforms.

It seems that both Linux ARM and Android have this problem from your reports. I can confirm neither of these because I don't have these devices.

Please post your platform information so I can make the change accordingly.

**Comment by hwf1324** [comment]
我不确定如何才能完整的描述我的平台信息，希望可以有用。

···
~ $ uname -a
Linux localhost 4.14.117-perf-g66aed98 #1 SMP PREEMPT Wed Dec 9 16:54:14 CST 2020 aarch64 Android
···

android version: 10
64-bit ABI: arm64-v8a
32-bit ABI: armeabi-v7a, armeabi

**Comment by SichangHe** [comment]
Quickjs does not support Linux on ARM, then.

**Comment by SichangHe** [comment]
I will change the build to use `duktype` on Linux ARM as I did with Windows.
However, `duktype` does not support all ECMAScript 2020 so some expressions would not be rendered correctly.
To deal with this, would a WASM build be helpful?

**Comment by SichangHe** [comment]
Would it build for you on the latest release, @hwf1324?

**Comment by hwf1324** [comment]
> Would it build for you on the latest release, @hwf1324?

是的，我从 `crates.io` 重新安装。
目前在我的设备上以可以成功构建。

**Comment by SichangHe** [comment]
That's great. Then, I assume this is completed.

For future references, the corresponding commit is [move tests to folder;complicate when to use duktape](https://github.com/lzanini/mdbook-katex/commit/15ecaeeed404ab2e548cd45809ea4e223103e6c4).
