### ISSUE TITLE
$\vec{a}$ inside a table cell breaks in a verbose and amusing way

### ISSUE THREAD

**Issue by str4d** [lzanini/mdbook-katex#3]
Using `$\vec{a}$` in regular text works as expected: an arrow is rendered above the `a`. Inspecting the page source, it appears this is implemented as an SVG path. However, if `$\vec{a}$` is placed inside a table cell, the SVG path is rendered as half a dozen extra cells containing the path coordinates.

**Comment by kknives** [comment]
It is incredibly amusing:
```
| Syntax | Description |
| --- | ----------- |
| $\vec{a}$ | Title |
| Paragraph | Text |
```
![katex_broken_table](https://user-images.githubusercontent.com/57328978/121365767-9048e980-c956-11eb-8cda-c3a9490aa5a7.png)

The html generated by the `katex` crate is colliding with the markdown parser.
I'll look into it

**Comment by kknives** [comment]
Well, I found why this happening:
`katex` crate renders `$\vec{a}$` as:
```html
<span class="katex"><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut" style="height:0.714em;vertical-align:0em;"></span><span class="mord accent"><span class="vlist-t"><span class="vlist-r"><span class="vlist" style="height:0.714em;"><span style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="mord mathnormal">a</span></span><span style="top:-3em;"><span class="pstrut" style="height:3em;"></span><span class="accent-body" style="left:-0.2355em;"><span class="overlay" style="height:0.714em;width:0.471em;"><svg width='0.471em' height='0.714em' style='width:0.471em' viewBox='0 0 471 714' preserveAspectRatio='xMinYMin'><path d='M377 20c0-5.333 1.833-10 5.5-14S391 0 397 0c4.667 0 8.667 1.667 12 5
3.333 2.667 6.667 9 10 19 6.667 24.667 20.333 43.667 41 57 7.333 4.667 11
10.667 11 18 0 6-1 10-3 12s-6.667 5-14 9c-28.667 14.667-53.667 35.667-75 63
-1.333 1.333-3.167 3.5-5.5 6.5s-4 4.833-5 5.5c-1 .667-2.5 1.333-4.5 2s-4.333 1
-7 1c-4.667 0-9.167-1.833-13.5-5.5S337 184 337 178c0-12.667 15.667-32.333 47-59
H213l-171-1c-8.667-6-13-12.333-13-19 0-4.667 4.333-11.333 13-20h359
c-16-25.333-24-45-24-59z'/></svg></span></span></span></span></span></span></span></span></span></span>
```

Each **newline/linebreak** in the `<path>` tag  is interpreted by the markdown parser as a new row...
Removing the newlines gives us:
![image](https://user-images.githubusercontent.com/57328978/121504687-d3ab6280-c9ff-11eb-9687-8a4228ca1936.png)

---
Before I issue a PR, I would like to see where the extra newlines are coming from, if it can be fixed upstream in `katex-rs` or even `libquickjs`

**Comment by kknives** [comment]
Nevermind, `katex-rs` and `libquickjs` are perfectly alright. It is `katex` (JS library not Rust crate) that outputs the newlines in the `path` tag: [demo](https://runkit.com/kknives/katex-html).

**Comment by lzanini** [comment]
Do you see this as being an issue with the `mdbook` crate, for not allowing newlines inside html, or as an issue with `mdbook-katex`, for yielding newlines in html where it shouldn't ?

**Comment by kknives** [comment]
The newlines inside the html tag are generally fine, `\vec{a}` renders fine outside of the table.

It is just that the markdown parser (`pulldown-cmark`) used by `mdBook` makes them into rows, when used in a table. There are other reported collisions with MathJax (rust-lang/mdBook#662, https://github.com/rust-lang/mdBook/issues/49#issuecomment-139385861).
But since, we use Katex as a preprocessor (we render math before the markdown parser looks at it), we avert those collisions.


This collision, however, seems like an edge case with the parser. The contents are the attributes of an html tag, but it breaks them into rows anyway.
We can try to fix this on our side, by just stripping all inline math (enclosed by `$`) html output of newlines, since inline math does not allow newlines (to my knowledge).
But we cannot do that for display blocks (enclosed by `$$`) html as they are allowed to have newlines in their output.

**Comment by SichangHe** [comment]
Should be fixed by https://github.com/SichangHe/mdbook-katex2/commit/825b6237a5c03ab629ba60dcccf4b2548c71f6f2.
