### ISSUE TITLE
Offline KaTeX

### ISSUE THREAD

**Issue by pozix604** [lzanini/mdbook-katex#7]
The current plugin is only able to use a CDN-sourced KaTeX implementation.

Please consider the ability to host an offline version of KaTeX. I'd like to be able to use mdbook in an offline context while still having the mathematical features.

Thanks!

**Comment by lzanini** [comment]
Hello, 

Using an offline version would require additional steps to set up the preprocessor, which is why I chose to use the CDN. 

You can do it manually though: download the css and js Katex files using the links from [here](https://katex.org/docs/browser.html), and load them using

```md
[output.html]
additional-css = ["path/to/katex.css"]
additional-js = ["path/to/katex.js"]
```

Then you should be able to use this preprocessor offline.

Let me know how it goes !
