### ISSUE TITLE
`\mathrm` after rendering generate unwanted '>' char

### ISSUE THREAD

**Issue by Sped0n** [lzanini/mdbook-katex#91]
## exmaple 1
```latex
\mathrm{n_{max} = \frac{m^h-1}{m-1}}
```

* correct rendering:

  <img width="675" alt="image" src="https://github.com/lzanini/mdbook-katex/assets/70063177/5ab49fc1-192a-4bf2-a022-1a94446526f5">

* unintended behavior:

  <img width="214" alt="image" src="https://github.com/lzanini/mdbook-katex/assets/70063177/2f0444c2-ff99-475f-9d0e-5da6cf67647e">

## example 2
```latex
\mathrm{\because n_{max} = \frac{m^h-1}{m-1}}\\
\mathrm{\therefore h_{min} = \log_m(n\times (m-1) + 1)}
```

* correct rendering:

  <img width="662" alt="image" src="https://github.com/lzanini/mdbook-katex/assets/70063177/11a4fbec-d4f8-41d3-9e3f-827f5f9f54dd">

* unintended behavior:

  <img width="331" alt="image" src="https://github.com/lzanini/mdbook-katex/assets/70063177/225726fd-009f-4b0f-8c3b-1399d4b32022">

**Comment by Sped0n** [comment]
btw inline rendering works fine

```latex
\mathrm{O(n)}
```

<img width="756" alt="image" src="https://github.com/lzanini/mdbook-katex/assets/70063177/1287dfea-fd79-4386-86f3-69c3fdd24dee">

**Comment by SichangHe** [comment]
I cannot reproduce. This is what I see:
![image](https://github.com/lzanini/mdbook-katex/assets/84777573/90fd0e74-1f62-4f26-950a-bd8083ffd38e)

**Comment by SichangHe** [comment]
Please tell me your mdBook-KaTeX version, provide me the related section in your `book.toml`.

Please also copy the rendered HTML if you know how to do that.

**Comment by SichangHe** [comment]
Thanks for your clear version and `book.toml`.

I see that you have these expressions in blockquotes. I am guessting that you put `> ` before every line of math expressions. The correct way (to use mdBook-KaTeX) would be to put `>` only before the starting line of each math expression, no matter they have empty lines in them or not.

![image](https://github.com/lzanini/mdbook-katex/assets/84777573/d98061d9-1627-4e09-bd62-1500f19d6f14)

This is because mdBook-KaTeX takes *everything* between the delimiters as a math expression, pre-renders it into *one single line* of HTML, and sends the whole book back to mdBook, where mdBook renders it as ordinary Markdown.

Does this solve the problem for you?

**Comment by SichangHe** [comment]
<details>
<summary>
This is the code for the above example.
</summary>

````markdown
```markdown
> $$
\mathrm{n_{max} = \frac{m^h-1}{m-1}}
$$
```

> $$
\mathrm{n_{max} = \frac{m^h-1}{m-1}}
$$

```markdown
> $$
> \mathrm{n_{max} = \frac{m^h-1}{m-1}}
> $$
```

> $$
> \mathrm{n_{max} = \frac{m^h-1}{m-1}}
> $$

```markdown
> $$
\mathrm{\because n_{max} = \frac{m^h-1}{m-1}}\\

\mathrm{\therefore h_{min} = \log_m(n\times (m-1) + 1)}
$$
```

> $$
\mathrm{\because n_{max} = \frac{m^h-1}{m-1}}\\

\mathrm{\therefore h_{min} = \log_m(n\times (m-1) + 1)}
$$
````

</details>

**Comment by Sped0n** [comment]
oops, my bad🤯
thanks for the thorough explanation

**Comment by SichangHe** [comment]
I'm glad that the problem is solved for you.

Apparently, some other renderes behave differently and prioritize quoteblocks over math expressions. mdBook-KaTeX is a pre-renderer, so I think it makes sense that we prioritize math expressions the most. However, we could prioritize quoteblocks, but it would require parsing them—we currently don't—and a more complicated codebase.
